// ***********************************************************************
// <copyright file="CoreMessageKeys.cs" company="CAI">
//     Copyright © CAI 2016
// </copyright>
// ***********************************************************************

namespace CAI.Core.Messages
{
    /// <summary>
    /// The collection of keys generated by the EN Core Messages resource file.
    /// </summary>
    public class CoreMessageKeys
    {
        /// <summary>
        /// The key for the message similar to "{0} was unable to be added.".
        /// </summary>
        public static readonly string FailedAdd = "FailedAdd";

        /// <summary>
        /// The key for the message similar to "{0} was unabled to be changed.".
        /// </summary>
        public static readonly string FailedAddOrUpdate = "FailedAddOrUpdate";

        /// <summary>
        /// The key for the message similar to "{0} was unable to be deleted.".
        /// </summary>
        public static readonly string FailedDelete = "FailedDelete";

        /// <summary>
        /// The key for the message similar to "{0} was unable to be updated.".
        /// </summary>
        public static readonly string FailedUpdate = "FailedUpdate";

        /// <summary>
        /// The key for the message similar to "Unauthorized access to resource: {0}".
        /// </summary>
        public static readonly string HttpStatusCode401 = "HttpStatusCode401";

        /// <summary>
        /// The key for the message similar to "Forbidden to access resource: {0}".
        /// </summary>
        public static readonly string HttpStatusCode403 = "HttpStatusCode403";

        /// <summary>
        /// The key for the message similar to "Failed to find resource: {0}".
        /// </summary>
        public static readonly string HttpStatusCode404 = "HttpStatusCode404";

        /// <summary>
        /// The key for the message similar to "Internal Server Error encountered in resource: {0}".
        /// </summary>
        public static readonly string HttpStatusCode500 = "HttpStatusCode500";

        /// <summary>
        /// The key for the message similar to "The request passed, but no changes were detected to be saved.".
        /// </summary>
        public static readonly string NoRecordsSaved = "NoRecordsSaved";

        /// <summary>
        /// The key for the message similar to "A fatal application error occurred. Please use Reference ID {0} when contacting support.".
        /// </summary>
        public static readonly string ProductionMessageForExceptions = "ProductionMessageForExceptions";

        /// <summary>
        /// The key for the message similar to "{0} successfully added.".
        /// </summary>
        public static readonly string SuccessfulAdd = "SuccessfulAdd";

        /// <summary>
        /// The key for the message similar to "{0} successfully changed.".
        /// </summary>
        public static readonly string SuccessfulAddOrUpdate = "SuccessfulAddOrUpdate";

        /// <summary>
        /// The key for the message similar to "{0} successfully deleted.".
        /// </summary>
        public static readonly string SuccessfulDelete = "SuccessfulDelete";

        /// <summary>
        /// The key for the message similar to "{0} successfully updated.".
        /// </summary>
        public static readonly string SuccessfulUpdate = "SuccessfulUpdate";

	}
}