nuget push Kore.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Domain.EF.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Domain.LiteDb.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Caching.Memory.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Containers.Unity.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Logging.Log4Net.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Logging.NLog.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Messages.Resource.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Pdf.ITextSharp.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Reporting.SSRS.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
nuget push Kore.Providers.Serialization.Newtonsoft.1.0.3.nupkg -Source https://www.nuget.org/api/v2/package
