nuget delete Kore 1.0.1 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Domain.EF 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Domain.LiteDb 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Caching.Memory 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Containers.Unity 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Logging.Log4Net 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Logging.NLog 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Messages.Resource 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Pdf.ITextSharp 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Reporting.SSRS 1.0.0 -Source https://www.nuget.org/api/v2/package
nuget delete Kore.Providers.Serialization.Newtonsoft 1.0.0 -Source https://www.nuget.org/api/v2/package
